export const PAGE_INTERPRET_HOME = 1;
export const PAGE_INTERPRET_MOOD = 2;
export const PAGE_INTERPRET_ORACLE = 3;
export const PAGE_INTERPRET_CREATE_ACCOUNT = 4;
export const PAGE_INTERPRET_LOADING = 5;
export const PAGE_DREAM_DETAILS = 6;
export const PAGE_LIBRARY = 7;
export const PAGE_INTERPRET_DREAM_STREAM = 8;
export const PAGE_EMAIL_REMINDER_POPUP = 9;
export const PAGE_EMAIL_REMINDER_POPUP_CLOSED = 10;
export const PAGE_DREAM_STREAM = 11;
export const PAGE_E_BOOK = 12;
export const PAGE_QUESTIONS = 13;
export const PAGE_LANDING_PAGE = 14;
export const PAGE_JOURNAL_MAIN = 15;



// PAGE_INTERPRET_HOME,
// PAGE_INTERPRET_MOOD,
// PAGE_INTERPRET_ORACLE,
// PAGE_INTERPRET_CREATE_ACCOUNT,
// PAGE_INTERPRET_LOADING,
// PAGE_DREAM_DETAILS,
// PAGE_LIBRARY,
// PAGE_INTERPRET_DREAM_STREAM,
// PAGE_EMAIL_REMINDER_POPUP,
// PAGE_EMAIL_REMINDER_POPUP_CLOSED,
// PAGE_DREAM_STREAM,
// PAGE_E_BOOK,
// PAGE_QUESTIONS,
// PAGE_LANDING_PAGE
